$todo = <<END
  puppet agent --test --server gate.demo.dp.ua
  systemctl stop firewalld
END

$mach_quant = 3

Vagrant.configure("2") do |config|
 
  config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory=256
      vb.cpus=1
      vb.check_guest_additions=false
  config.vm.synced_folder "src/sis", "/var/www/html", type: "rsync"
  config.vm.box_check_update=false
  config.vm.box_download_insecure=true
  config.vm.box="puppetlabs/centos-7.2-64-puppet"
  config.vm.provision "shell", inline: $todo
  config.vm.boot_timeout=60
 end

(1..$mach_quant).each do |i|
    config.vm.define "node#{i}" do |node|
        node.vm.network "public_network", ip: "192.168.1.#{24+i}"
        node.vm.hostname = "node#{i}"
    end
end
  
end
